services:
  - type: web
    name: ecommerce-backend
    runtime: node
    region: ohio
    plan: free
    buildCommand: |
      npm ci
      npm run build
    startCommand: npx typeorm migration:run -d dist/src/data-source.js && node dist/src/main
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: ecommerce-db
    plan: free
    databaseName: ecommerce_prod
